### ISSUE TITLE
Payment received but order not placed

### ISSUE THREAD

**Issue by slaurro** [paylike/plugin-magento-1.9#20]
Paylike plugin version 1.0.5 on a magento 1.9.2 store. Once every week or so, we find a payment that is visible in the paylike.io dashboard but no order is placed for it. I'm guessing for whatever reason the customer isn't redirected to the success page so the order isn't placed. Absolutely nothing wrong in the logs and we can't reproduce the problem.

**Comment by ionutcalara** [comment]
Hi @slaurro, sorry to hear you are having issues. One thing that we always recommend is to install the latest version which in this case is v1.1.1. However please test on a staging website first, and make sure everything works. 

For the issue you are having, due to the fact that you cannot replicate it consistently, we will need a debugging tool installed. We recommend sentry.io or bugsnag. 

Since the paylike popup works through javascript on the client-side, any javascript errors might break the payment gateway.

Another possible problem is server-side validation as it would reject the order after the payment is made.  Make sure all validation happens before the payment via ajax. 

Once you install a debugging tool and have recordings of the sessions please reach out through our support with them and we will investigate the issues further. 

For the existing broken orders, you can manually create them using the information on paylike.io. We also encourage contacting the clients to explain the situation and see if they have any valuable insight. 

Looking forward to the debug information. 
Ionut
